version: '2'

services:
  influxdb:
    restart: always
    image: influxdb:1.8.10
    container_name: docker-speedtest-grafana_influxdb
    ports:
      - "8086:8086"
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=speedtest"
    networks:
      internal:
        ipv4_address: 172.30.1.2

  grafana:
    restart: always
    image: grafana/grafana:10.4.2
    container_name: docker-speedtest-grafana_grafana
    volumes:
      - "./docker/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    networks:
      internal:
        ipv4_address: 172.30.1.3
    depends_on:
      - influxdb

  speedtest:
    restart: always
    image: docker-speedtest-grafana:latest
    container_name: docker-speedtest-grafana_speedtest
    environment:
      - "SPEEDTEST_INTERVAL=${SPEEDTEST_SPEEDTEST_INTERVAL}"
      - "SPEEDTEST_HOST=${SPEEDTEST_HOST}"
    networks:
      internal:
        ipv4_address: 172.30.1.4
      priv_lan:
        ipv4_address: 192.168.2.132
    depends_on:
      - influxdb

networks:
  # Create the internal network
  internal:
    ipam:
      config:
        - subnet: 172.30.1.0/29

  # The priv_lan network is already setup, so it is an 'external' network
  priv_lan:
    external: true
    name: 1_server_lan
